# R - `ccgarch`
Dynamic conditional correlation (DCC) generalized autoregressive conditional heteroskedastic (GARCH) model  
This is required to estimate the *marginal expected shortfall* (MES) and from that SRISK.
### `ccgarch`
https://cran.r-project.org/web/packages/ccgarch/  
https://github.com/cran/ccgarch    
https://www.r-project.org/conferences/useR-2008/slides/Nakatani.pdf  
### `rmgarch`
https://cran.r-project.org/web/packages/rmgarch/     
http://www.unstarched.net/2013/01/03/the-garch-dcc-model-and-2-stage-dccmvt-estimation/    
(Unable to install `rmgarch` on Azure.)

In [5]:
# install.packages("rugarch")

In [2]:
if(!require(ccgarch)){
    install.packages("ccgarch")
    library(ccgarch)
}

Loading required package: ccgarch
Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘ccgarch’”Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)


# Package `ccgarch` sample code

## Simulation
Simulating data from the original DCC-GARCH(1,1) process

In [3]:
  nobs <- 1000
  a <- c(0.003, 0.005, 0.001)
  A <- diag(c(0.2,0.3,0.15))
  B <- diag(c(0.75, 0.6, 0.8))
  uncR <- matrix(c(1.0, 0.4, 0.3, 0.4, 1.0, 0.12, 0.3, 0.12, 1.0),3,3)
  dcc.para <- c(0.01,0.98)
  dcc.data <- dcc.sim(nobs, a, A, B, uncR, dcc.para, model="diagonal")

Outputs are:
* `z`
* `std.z`
* `dcc`
* `h`
* `eps`

In [4]:
lapply(dcc.data,head)

$z
           [,1]       [,2]       [,3]
[1,]  0.5206696 -0.8910939  0.3819692
[2,]  0.4550651  1.3472001  1.2939447
[3,] -2.1674543  1.2606279  0.1054293
[4,]  1.5313007 -1.4033190  0.9097230
[5,] -1.4804667 -1.4289710  1.1540253
[6,] -0.4845374 -0.9756432 -0.2019444

$std.z
           [,1]       [,2]       [,3]
[1,]  0.5206696 -0.6936783  0.5345657
[2,]  0.4550651  1.4215491  1.3860747
[3,] -2.1674543  0.5503189 -0.6786519
[4,]  1.5313007 -0.9131533  1.3811089
[5,] -1.4804667 -1.7713403  0.4619071
[6,] -0.4845374 -1.0733593 -0.3724337

$dcc
     [,1]      [,2]      [,3]      [,4] [,5]      [,6]      [,7]      [,8] [,9]
[1,]    1 0.3002125 0.3709620 0.3002125    1 0.1255535 0.3709620 0.1255535    1
[2,]    1 0.2965519 0.3719924 0.2965519    1 0.1215184 0.3719924 0.1215184    1
[3,]    1 0.3007827 0.3737120 0.3007827    1 0.1378266 0.3737120 0.1378266    1
[4,]    1 0.2827120 0.3777220 0.2827120    1 0.1336100 0.3777220 0.1336100    1
[5,]    1 0.2660429 0.3896211 0.2660429    1 0.1197954 0.3896211 0.1197954    1
[6,]    1 0.2854389 0.3776143 0.2854389    1 0.1102152 0.3776143 0.1102152    1

$h
           [,1]       [,2]       [,3]
[1,] 0.05341312 0.05093288 0.02490701
[2,] 0.04595586 0.04291224 0.02199323
[3,] 0.03937025 0.05676248 0.02493260
[4,] 0.06951885 0.04421466 0.02266855
[5,] 0.08774183 0.04258930 0.02562075
[6,] 0.10726856 0.07064263 0.02231656

$eps
            [,1]       [,2]        [,3]
[1,]  0.12033341 -0.1565515  0.08436492
[2,]  0.09755376  0.2944777  0.20555645
[3,] -0.43006492  0.1311128 -0.10715955
[4,]  0.40374928 -0.1920113  0.20794086
[5,] -0.43853271 -0.3655546  0.07393509
[6,] -0.15869511 -0.2852847 -0.05563686

## Estimation - `dcc.estimation`
Estimating a DCC-GARCH(1,1) model  
See **P6** of https://cran.r-project.org/web/packages/ccgarch/ccgarch.pdf   
https://www.rdocumentation.org/packages/ccgarch/versions/0.2.3/topics/dcc.estimation  

In [10]:
dcc.results <- dcc.estimation(inia=a, iniA=A, iniB=B, ini.dcc=dcc.para, 
        dvar=dcc.data$eps, model="diagonal")

****************************************************************
*  Estimation has been completed.                              *
*  The outputs are saved in a list with components:            *
*    out    : the estimates and their standard errors          *
*    loglik : the value of the log-likelihood at the estimates *
*    h      : a matrix of estimated conditional variances      *
*    DCC    : a matrix of DCC estimates                        *
*    std.resid : a matrix of the standardised residuals        *
*    first  : the results of the first stage estimation        *
*    second : the results of the second stage estimation       *
****************************************************************


#### Parameter estimates and their robust standard errors `dcc.results$out`

Outputs are:
* `out` - parameter estimates and their standard errors: vector `a`, matrices `A` & `B`
* `loglik` - the value of the log-likelihood at the estimates (scalar)
* `h` - estimated conditional variances ($T\times N$)
* `DCC` - a matrix of DCC estimates  ($T\times N^2$)
* `std.resid` a matrix of the standardised residuals ($T\times N$)
* `first `
* `second`

In [9]:
dcc.results$out

a1           a2          a3          A11          A22       
estimates 0.0017628193 0.003995321 0.001298869 0.1175401033 0.28682881
std.err   0.0006186365 0.022809737 0.026400181 0.0008742992 0.03817618
          A33        B11          B22        B33        dcc alpha   dcc beta  
estimates 0.17806329 0.8479426868 0.66384874 0.76507433 0.006945695 0.98294356
std.err   0.03701335 0.0004362676 0.03416077 0.04367185 0.004102339 0.01298284

In [7]:
dcc.results$loglik

[1] 977.9982

In [11]:
head(dcc.results$h)

[,1]       [,2]       [,3]      
[1,] 0.05827177 0.06497643 0.02330323
[2,] 0.05287593 0.05415955 0.02039493
[3,] 0.04771718 0.06482204 0.02442629
[4,] 0.06396398 0.05195810 0.02203153
[5,] 0.07516123 0.04906254 0.02585398
[6,] 0.08809948 0.07489441 0.02205245

In [12]:
head(dcc.results$DCC)

[,1] [,2]      [,3]      [,4]      [,5] [,6]      [,7]      [,8]      [,9]
[1,] 1    0.3880568 0.4194326 0.3880568 1    0.2349826 0.4194326 0.2349826 1   
[2,] 1    0.3850584 0.4205506 0.3850584 1    0.2320362 0.4205506 0.2320362 1   
[3,] 1    0.3864534 0.4215064 0.3864534 1    0.2418037 0.4215064 0.2418037 1   
[4,] 1    0.3738472 0.4245053 0.3738472 1    0.2386361 0.4245053 0.2386361 1   
[5,] 1    0.3604719 0.4332746 0.3604719 1    0.2281220 0.4332746 0.2281220 1   
[6,] 1    0.3723140 0.4239968 0.3723140 1    0.2205676 0.4239968 0.2205676 1

#### DCC estimates - `dcc.results$DCC`

Instead of a 3-d $T\times N\times N$ `array`, the `DCC` result is a 2-d $T\times N^2$ `matrix`, so we have to reshape it.

In [13]:
dim(dcc.results$DCC)

[1] 1000    9

In [14]:
dcc.results$DCC[1,]

[1] 1.0000000 0.3880568 0.4194326 0.3880568 1.0000000 0.2349826 0.4194326
[8] 0.2349826 1.0000000

In [15]:
matrix(dcc.results$DCC[1,],nrow = 3,ncol = 3)

[,1]      [,2]      [,3]     
[1,] 1.0000000 0.3880568 0.4194326
[2,] 0.3880568 1.0000000 0.2349826
[3,] 0.4194326 0.2349826 1.0000000

In [ ]:
array(dcc.results$DCC, dim = c(50,3,3))[1,,]