# Py - `rpy2` (Python 3.6 `rpy2` 2.9.1)

https://rpy2.bitbucket.io/  
`rpy2` is an interface to R running embedded in a Python process.  
This notebook is for **Python 3.6** and **`rpy2` 2.9.1.**    
This runs locally, but not on Azure.

### Purpose:
Mix python & R code in a single notebook.  
https://stackoverflow.com/questions/39008069/r-and-python-in-one-jupyter-notebook  
https://rpy2.github.io/doc/v2.9.x/html/interactive.html?highlight=magic#overview   

#### Problems
On Azure notebooks, only works for Python 2? https://github.com/Microsoft/AzureNotebooks/issues/35 
https://stats.stackexchange.com/questions/6056/problems-with-librblas-so-on-ubuntu-with-rpy2  

### Install & load library

In [1]:
!pip install rpy2

In [2]:
import rpy2
rpy2.__path__

['C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Anaconda3_64\\lib\\site-packages\\rpy2-2.9.1-py3.6-win-amd64.egg\\rpy2']

In [3]:
print(rpy2.__version__)

2.9.1


In [4]:
%load_ext rpy2.ipython

### `sessionInfo`

In [6]:
%R sessionInfo()

R object with classes: ('sessionInfo',) mapped to:
<ListVector - Python:0x00000161B4E81408 / R:0x00000161B770CC90>
[ListVector, StrVector, StrVector, StrVector, ..., ListVector, StrVector, StrVector, StrVector]
R object with classes: ('sessionInfo',) mapped to:
<ListVector - Python:0x00000161B4E81408 / R:0x00000161B770CC90>
[ListVector, StrVector, StrVector, StrVector, ..., ListVector, StrVector, StrVector, StrVector]
  platform: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x00000161B9A41C48 / R:0x00000161B9B02F58>
['x86_64-w64-mingw32/x64 (64-bit)']
  locale: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x00000161B9A41A48 / R:0x00000161B9B02E98>
['LC_COLLATE=English_United Kingdom.1252;LC_CTYPE=...]
  running: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x00000161B9A41188 / R:0x00000161B9B04920>
['Windows 10 x64 (build 16299)']
...
R object with classes: ('sessionInfo',) mapped to:
<ListVector - Python:0x00000161B4E81408 / R:0x00000161B770CC90>
[ListVector, StrVector, StrVector, StrVector, ..., ListVector, StrVector, StrVector, StrVector]
  loadedOnly: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x00000161B9A38388 / R:0x00000161B9BCB8C8>
['default']
  matprod: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x00000161B9A38308 / R:0x00000161B9BCB628>
['']
  BLAS: <class 'rpy2.robjects.vectors.StrVector'>
  R object with classes: ('character',) mapped to:
<StrVector - Python:0x00000161B9A38EC8 / R:0x00000161B9BCB598>
['']

### `robjects`

In [7]:
import rpy2.robjects as robjects

#### Package module

In [8]:
# import rpy2's package module
import rpy2.robjects.packages as rpackages

# import R's utility package
utils = rpackages.importr('utils')

# select a mirror for R packages
utils.chooseCRANmirror(ind=1) # select the first mirror in the list

rpy2.rinterface.NULL

### Installed packages

In [5]:
%%R
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]

In [6]:
%R print(ip, row.names=FALSE)

Package   Version
1     assertthat     0.2.0
3             BH  1.65.0-1
4          bindr       0.1
5       bindrcpp       0.2
6            bit    1.1-12
7          bit64     0.9-7
8           blob     1.1.0
9            cli     1.0.0
11        crayon     1.3.4
13           DBI       0.7
14        dbplyr     1.1.0
15        digest    0.6.13
16         dplyr     0.7.4
17          glue     1.2.0
21      magrittr       1.5
22       memoise     1.1.0
24         olapR     1.0.0
26        pillar     1.0.1
27     pkgconfig     2.0.1
28         plogr     0.1-1
29         purrr     0.2.4
30            R6     2.2.2
31          Rcpp   0.12.14
32     RevoUtils    10.0.8
33         rlang     0.1.6
34         RODBC    1.3-15
35       RSQLite       2.0
37     sqlrutils     1.0.0
41        tibble     1.4.1
43  translations     3.4.3
44          utf8     1.1.2

### Magics

https://rpy2.github.io/doc/v2.9.x/html/interactive.html?highlight=magic#module-rpy2.ipython.rmagic

In [7]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


In [13]:
%R X=c(1,4,5,7)

array([ 1.,  4.,  5.,  7.])

In [14]:
%%R
X2=c(1,2,3,4)
mean(X2)

In [15]:
%R mean(X)

array([ 4.25])

In [17]:
%%R
Y = c(2,4,3,9)
s = summary(lm(Y~X))

In [18]:
%R s

R object with classes: ('summary.lm',) mapped to:
<ListVector - Python:0x00000161B9B44788 / R:0x00000161BA9B79E0>
[Vector, Formula, FloatVector, Matrix, ..., FloatVector, FloatVector, FloatVector, Matrix]
  call: <class 'rpy2.robjects.vectors.Vector'>
  R object with classes: ('lm',) mapped to:
<Vector - Python:0x00000161B9E92248 / R:0x00000161BABDB020>
[RObject, Vector]
  terms: <class 'rpy2.robjects.Formula'>
  R object with classes: ('terms', 'formula') mapped to:
<Formula - Python:0x00000161BA0B1048 / R:0x00000161BABBAFC8>
  residuals: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BA0B3308 / R:0x00000161BB49C8D8>
[0.880000, -0.240000, -2.280000, 1.640000]
  coefficients: <class 'rpy2.robjects.vectors.Matrix'>
  R object with classes: ('matrix',) mapped to:
<Matrix - Python:0x00000161B9B4F188 / R:0x00000161BA5D4928>
[0.080000, 1.040000, 2.300029, 0.482217, 0.034782, 2.156705, 0.975413, 0.163752]
...
  sigma: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BA0B4808 / R:0x00000161BB4F2BC0>
[0.699310]
  df: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BA0B4248 / R:0x00000161BB4F2B90>
[0.548966]
  r.squared: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BA0B4DC8 / R:0x00000161BB4CC878>
[4.651376, 1.000000, 2.000000]
  adj.r.squared: <class 'rpy2.robjects.vectors.Matrix'>
  R object with classes: ('matrix',) mapped to:
<Matrix - Python:0x00000161BA0B4688 / R:0x00000161BB4CC7E8>
[1.213333, -0.226667, -0.226667, 0.053333]

In [19]:
%R sd(X)

array([ 2.5])

### Matloff

http://heather.cs.ucdavis.edu/~matloff/rpy2.html

In [ ]:
from rpy2.robjects import r
r('x <- rnorm(100)')  # generate x at R
r('y <- x + rnorm(100,sd=0.5)')  # generate y at R

In [26]:
r('plot(x,y)')  # have R plot them

rpy2.rinterface.NULL

In [30]:
r('lmout <- lm(y~x)')  # run the regression
r('print(lmout)')  # print from R

R object with classes: ('lm',) mapped to:
<ListVector - Python:0x00000161B9E14EC8 / R:0x00000161BBCCF260>
[FloatVector, FloatVector, FloatVector, IntVector, ..., ListVector, Vector, Formula, DataFrame]
  coefficients: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161B9E14388 / R:0x00000161BB06AD58>
[0.035741, 1.029290]
  residuals: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161B9E14608 / R:0x00000161BBCCD780>
[-0.127094, -0.649659, -0.192780, 0.070212, ..., -0.152575, -0.437929, 0.266562, 0.877631]
  effects: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161B9E14FC8 / R:0x00000161BBCCDAD0>
[-2.298883, 11.303722, -0.182198, 0.111087, ..., -0.291888, -0.489297, 0.274761, 0.885565]
  rank: <class 'rpy2.robjects.vectors.IntVector'>
  R object with classes: ('integer',) mapped to:
<IntVector - Python:0x00000161B9E148C8 / R:0x00000161BBC01B48>
[2]
...
R object with classes: ('lm',) mapped to:
<ListVector - Python:0x00000161B9E14EC8 / R:0x00000161BBCCF260>
[FloatVector, FloatVector, FloatVector, IntVector, ..., ListVector, Vector, Formula, DataFrame]
  qr: <class 'rpy2.robjects.vectors.Vector'>
  R object with classes: ('lm',) mapped to:
<Vector - Python:0x00000161BCFE7DC8 / R:0x00000161BBAEB618>
[RObject, Vector]
  df.residual: <class 'rpy2.robjects.Formula'>
  R object with classes: ('terms', 'formula') mapped to:
<Formula - Python:0x00000161BCFE7CC8 / R:0x00000161BBB0C2F0>
R object with classes: ('lm',) mapped to:
<ListVector - Python:0x00000161B9E14EC8 / R:0x00000161BBCCF260>
[FloatVector, FloatVector, FloatVector, IntVector, ..., ListVector, Vector, Formula, DataFrame]

In [28]:
loclmout = r('lmout') # download lmout from R to Python
print(loclmout)  # print locally
#print(loclmout.r['coefficients'])  # print one component



Call:

lm(formula = y ~ x)



Coefficients:

(Intercept)            x  

    0.03574      1.02929  





In [29]:
loclmout

R object with classes: ('lm',) mapped to:
<ListVector - Python:0x00000161BCFE74C8 / R:0x00000161BB5A1100>
[FloatVector, FloatVector, FloatVector, IntVector, ..., ListVector, Vector, Formula, DataFrame]
  coefficients: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BCFE7B48 / R:0x00000161BAE215F8>
[0.035741, 1.029290]
  residuals: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BCFE7B08 / R:0x00000161BB59FBE0>
[-0.127094, -0.649659, -0.192780, 0.070212, ..., -0.152575, -0.437929, 0.266562, 0.877631]
  effects: <class 'rpy2.robjects.vectors.FloatVector'>
  R object with classes: ('numeric',) mapped to:
<FloatVector - Python:0x00000161BCFE7FC8 / R:0x00000161BB59FF30>
[-2.298883, 11.303722, -0.182198, 0.111087, ..., -0.291888, -0.489297, 0.274761, 0.885565]
  rank: <class 'rpy2.robjects.vectors.IntVector'>
  R object with classes: ('integer',) mapped to:
<IntVector - Python:0x00000161B9B4B4C8 / R:0x00000161BBA6D1E8>
[2]
...
R object with classes: ('lm',) mapped to:
<ListVector - Python:0x00000161BCFE74C8 / R:0x00000161BB5A1100>
[FloatVector, FloatVector, FloatVector, IntVector, ..., ListVector, Vector, Formula, DataFrame]
  qr: <class 'rpy2.robjects.vectors.Vector'>
  R object with classes: ('lm',) mapped to:
<Vector - Python:0x00000161B9E14FC8 / R:0x00000161BB941240>
[RObject, Vector]
  df.residual: <class 'rpy2.robjects.Formula'>
  R object with classes: ('terms', 'formula') mapped to:
<Formula - Python:0x00000161B9E14E08 / R:0x00000161BB9642D0>
R object with classes: ('lm',) mapped to:
<ListVector - Python:0x00000161BCFE74C8 / R:0x00000161BB5A1100>
[FloatVector, FloatVector, FloatVector, IntVector, ..., ListVector, Vector, Formula, DataFrame]

### Plotting example

https://stackoverflow.com/questions/39008069/r-and-python-in-one-jupyter-notebook

In [10]:
#%R library("ggplot2", lib.loc="C:/Users/Ian Buckley/Documents/R/win-library/3.3")
%R install.packages("ggplot2")


Error in install.packages("ggplot2") : unable to install packages


PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\IANBUC~1\\AppData\\Local\\Temp\\tmpf3hdvr3s\\Rplots001.png'

In [8]:
%R library("ggplot2")


Error in library("ggplot2") : there is no package called 'ggplot2'


PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\IANBUC~1\\AppData\\Local\\Temp\\tmptz9d7_a9\\Rplots001.png'

In [ ]:
# enables the %%R magic, not necessary if you've already done this
%load_ext rpy2.ipython

import pandas as pd
df = pd.DataFrame({
    'cups_of_coffee': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    'productivity': [2, 5, 6, 8, 9, 8, 0, 1, 0, -1]
})

In [44]:
# import df from global environment
# make default figure size 5 by 5 inches with 200 dpi resolution
# Note that %%R has to be at start of cell!!!

In [ ]:
%%R -i df -w 5 -h 5 --units in -r 200
install.packages("ggplot2", repos='http://cran.us.r-project.org', quiet=TRUE)
library(ggplot2)
ggplot(df, aes(x=cups_of_coffee, y=productivity)) + geom_line()

Objects can be passed back and forth between rpy2 and python via the -i -o flags in line:

In [ ]:
Z = np.array([1,4,5,10])

In [ ]:
%R -i Z mean(Z)

In [ ]:
%R -o W W=Z*mean(Z)

In [ ]:
W